# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Awar_app', '0003_auto_20191030_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='img_name',
        ),
    ]
