# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Awar_app', '0004_auto_20191030_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_name',
            new_name='title',
        ),
    ]
