# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-31 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_caption',
            new_name='description',
        ),
    ]
